//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBHelper
{
    using System;
    using System.Collections.Generic;
    
    public partial class Verification
    {
        public int no { get; set; }
        public string PTTID { get; set; }
        public int VerifyType { get; set; }
        public bool IsConfirmed { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateDateIP { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string ModifyDateIP { get; set; }
        public Nullable<System.DateTime> AvailableDate { get; set; }
        public string Base5 { get; set; }
    }
}
